# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CD

on:
  push:
    branches: [ main, release/1.0, version/1.0 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
       java-version: 11
       
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
    - name: Change gradlew permissions
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
     
    - name: Upload APK
      if: ${{ success() }}
      uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
        file_path: 'app/build/outputs/apk/debug/app-debug.apk'
        file_name: 'Nadosunbae.apk'
        file_type: 'apk'
        initial_comment: '${{ github.ref }} 테스트 APK 배포 성공'

    - name: On Failed
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#ff0000'
        SLACK_ICON: https://user-images.githubusercontent.com/37872134/156731525-c27edd80-3e15-42ec-8bc3-7b82a54bd7c1.jpg
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TITLE: 'APK Build Failed'
        MSG_MINIMAL: true
        SLACK_USERNAME: APK_GEN
        SLACK_MESSAGE: '오류를 확인해주세요...'
